name: google_maps_custom_marker
description: "A flexible package for creating various shapes of highly customizable markers with optional labels."
version: 1.0.0
repository: "https://github.com/Robert01101101/google_maps_custom_marker"
issue_tracker: "https://github.com/Robert01101101/google_maps_custom_marker/issues"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: